
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.json
{
public sealed partial class Sound : Luban.BeanBase
{
    public Sound(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["location"].IsString) { throw new SerializationException(); }  Location = _buf["location"]; }
        { if(!_buf["group"].IsString) { throw new SerializationException(); }  Group = _buf["group"]; }
        { if(!_buf["loop"].IsBoolean) { throw new SerializationException(); }  Loop = _buf["loop"]; }
        { if(!_buf["volume"].IsNumber) { throw new SerializationException(); }  Volume = _buf["volume"]; }
        { if(!_buf["priority"].IsNumber) { throw new SerializationException(); }  Priority = _buf["priority"]; }
        { if(!_buf["mute"].IsBoolean) { throw new SerializationException(); }  Mute = _buf["mute"]; }
        { if(!_buf["fade_in_seconds"].IsNumber) { throw new SerializationException(); }  FadeInSeconds = _buf["fade_in_seconds"]; }
        { if(!_buf["pitch"].IsNumber) { throw new SerializationException(); }  Pitch = _buf["pitch"]; }
        { if(!_buf["pan_stereo"].IsNumber) { throw new SerializationException(); }  PanStereo = _buf["pan_stereo"]; }
        { if(!_buf["spatial_blend"].IsNumber) { throw new SerializationException(); }  SpatialBlend = _buf["spatial_blend"]; }
        { if(!_buf["max_distance"].IsNumber) { throw new SerializationException(); }  MaxDistance = _buf["max_distance"]; }
        { if(!_buf["doppler_level"].IsNumber) { throw new SerializationException(); }  DopplerLevel = _buf["doppler_level"]; }
    }

    public static Sound DeserializeSound(JSONNode _buf)
    {
        return new Sound(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 音频资源路径
    /// </summary>
    public readonly string Location;
    /// <summary>
    /// 音频组
    /// </summary>
    public readonly string Group;
    /// <summary>
    /// 是否循环
    /// </summary>
    public readonly bool Loop;
    /// <summary>
    /// 音量
    /// </summary>
    public readonly float Volume;
    /// <summary>
    /// 优先级
    /// </summary>
    public readonly int Priority;
    /// <summary>
    /// 是否静音
    /// </summary>
    public readonly bool Mute;
    /// <summary>
    /// 淡入时长(秒)
    /// </summary>
    public readonly float FadeInSeconds;
    /// <summary>
    /// 音调
    /// </summary>
    public readonly float Pitch;
    /// <summary>
    /// 立体声方位
    /// </summary>
    public readonly float PanStereo;
    /// <summary>
    /// 空间混合
    /// </summary>
    public readonly float SpatialBlend;
    /// <summary>
    /// 最大听距
    /// </summary>
    public readonly float MaxDistance;
    /// <summary>
    /// 多普勒等级
    /// </summary>
    public readonly float DopplerLevel;
   
    public const int __ID__ = 80074991;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "location:" + Location + ","
        + "group:" + Group + ","
        + "loop:" + Loop + ","
        + "volume:" + Volume + ","
        + "priority:" + Priority + ","
        + "mute:" + Mute + ","
        + "fadeInSeconds:" + FadeInSeconds + ","
        + "pitch:" + Pitch + ","
        + "panStereo:" + PanStereo + ","
        + "spatialBlend:" + SpatialBlend + ","
        + "maxDistance:" + MaxDistance + ","
        + "dopplerLevel:" + DopplerLevel + ","
        + "}";
    }
}
}

