
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.json
{
public sealed partial class SoundGroup : Luban.BeanBase
{
    public SoundGroup(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["Name"].IsString) { throw new SerializationException(); }  Name = _buf["Name"]; }
        { if(!_buf["MixerGroupPath"].IsString) { throw new SerializationException(); }  MixerGroupPath = _buf["MixerGroupPath"]; }
        { if(!_buf["AvoidBeingReplacedBySamePriority"].IsBoolean) { throw new SerializationException(); }  AvoidBeingReplacedBySamePriority = _buf["AvoidBeingReplacedBySamePriority"]; }
        { if(!_buf["Mute"].IsBoolean) { throw new SerializationException(); }  Mute = _buf["Mute"]; }
        { if(!_buf["Volume"].IsNumber) { throw new SerializationException(); }  Volume = _buf["Volume"]; }
        { if(!_buf["AgentCount"].IsNumber) { throw new SerializationException(); }  AgentCount = _buf["AgentCount"]; }
    }

    public static SoundGroup DeserializeSoundGroup(JSONNode _buf)
    {
        return new SoundGroup(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 音频组名
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// Mixer 组路径
    /// </summary>
    public readonly string MixerGroupPath;
    /// <summary>
    /// 是否避免被同优先级替换
    /// </summary>
    public readonly bool AvoidBeingReplacedBySamePriority;
    /// <summary>
    /// 是否静音
    /// </summary>
    public readonly bool Mute;
    /// <summary>
    /// 音量
    /// </summary>
    public readonly float Volume;
    /// <summary>
    /// Agent 数量
    /// </summary>
    public readonly int AgentCount;
   
    public const int __ID__ = 1628793552;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "Name:" + Name + ","
        + "MixerGroupPath:" + MixerGroupPath + ","
        + "AvoidBeingReplacedBySamePriority:" + AvoidBeingReplacedBySamePriority + ","
        + "Mute:" + Mute + ","
        + "Volume:" + Volume + ","
        + "AgentCount:" + AgentCount + ","
        + "}";
    }
}
}

