
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;

namespace cfg.json
{
public partial class Tables
{
    public TbSound TbSound {get; }
    public TbSoundGroup TbSoundGroup {get; }
    public TbUIPanel TbUIPanel {get; }

    public Tables(System.Func<string, JSONNode> loader)
    {
        TbSound = new TbSound(loader("tbsound"));
        TbSoundGroup = new TbSoundGroup(loader("tbsoundgroup"));
        TbUIPanel = new TbUIPanel(loader("tbuipanel"));
        ResolveRef();
    }
    
    private void ResolveRef()
    {
        TbSound.ResolveRef(this);
        TbSoundGroup.ResolveRef(this);
        TbUIPanel.ResolveRef(this);
    }
}

}

