
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.json
{
public partial class TbSoundGroup
{
    private readonly System.Collections.Generic.Dictionary<int, SoundGroup> _dataMap;
    private readonly System.Collections.Generic.List<SoundGroup> _dataList;
    
    public TbSoundGroup(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, SoundGroup>(count);
        _dataList = new System.Collections.Generic.List<SoundGroup>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            SoundGroup _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.json.SoundGroup.DeserializeSoundGroup(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, SoundGroup> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<SoundGroup> DataList => _dataList;

    public SoundGroup GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public SoundGroup Get(int key) => _dataMap[key];
    public SoundGroup this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

