
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.json
{
public partial class TbUIPanel
{
    private readonly System.Collections.Generic.Dictionary<int, UIPanel> _dataMap;
    private readonly System.Collections.Generic.List<UIPanel> _dataList;
    
    public TbUIPanel(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, UIPanel>(count);
        _dataList = new System.Collections.Generic.List<UIPanel>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            UIPanel _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.json.UIPanel.DeserializeUIPanel(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, UIPanel> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<UIPanel> DataList => _dataList;

    public UIPanel GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public UIPanel Get(int key) => _dataMap[key];
    public UIPanel this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

