
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.json
{
public sealed partial class UIPanel : Luban.BeanBase
{
    public UIPanel(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["location"].IsString) { throw new SerializationException(); }  Location = _buf["location"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["groupName"].IsString) { throw new SerializationException(); }  GroupName = _buf["groupName"]; }
        { if(!_buf["canvas_mode"].IsNumber) { throw new SerializationException(); }  CanvasMode = _buf["canvas_mode"]; }
        { if(!_buf["sort_order"].IsNumber) { throw new SerializationException(); }  SortOrder = _buf["sort_order"]; }
        { if(!_buf["pauseCoveredUIForm"].IsBoolean) { throw new SerializationException(); }  PauseCoveredUIForm = _buf["pauseCoveredUIForm"]; }
        { if(!_buf["loader"].IsNumber) { throw new SerializationException(); }  Loader = _buf["loader"]; }
    }

    public static UIPanel DeserializeUIPanel(JSONNode _buf)
    {
        return new UIPanel(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Location;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// 分组
    /// </summary>
    public readonly string GroupName;
    /// <summary>
    /// 挂载界面根节点
    /// </summary>
    public readonly int CanvasMode;
    /// <summary>
    /// 深度
    /// </summary>
    public readonly int SortOrder;
    /// <summary>
    /// 是否关闭底下界面
    /// </summary>
    public readonly bool PauseCoveredUIForm;
    public readonly int Loader;
   
    public const int __ID__ = 295209936;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "location:" + Location + ","
        + "desc:" + Desc + ","
        + "groupName:" + GroupName + ","
        + "canvasMode:" + CanvasMode + ","
        + "sortOrder:" + SortOrder + ","
        + "pauseCoveredUIForm:" + PauseCoveredUIForm + ","
        + "loader:" + Loader + ","
        + "}";
    }
}
}

