
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



namespace cfg.json
{ 
    /// <summary>
    /// 武器Id(与TbWeapon.id一致)
    /// </summary>
    public enum WeaponId
    {
        /// <summary>
        /// 玩家步枪
        /// </summary>
        Rifle = 0,
        /// <summary>
        /// 玩家霰弹
        /// </summary>
        Shotgun = 1,
        /// <summary>
        /// 玩家RPG
        /// </summary>
        RPG = 2,
        /// <summary>
        /// 玩家能量步枪
        /// </summary>
        Energy = 3,
        /// <summary>
        /// 玩家狙击
        /// </summary>
        Sniper = 4,
        /// <summary>
        /// 玩家弩
        /// </summary>
        Crossbow = 5,
        /// <summary>
        /// EnemyWeapons/EnemyGun_Canon_A
        /// </summary>
        EnemyCanonA = 6,
    }

} 

