// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;

namespace GamePlay
{
    public readonly struct RedDot_Record
    {
        public RedDot_Record(int id, string name)
        {
            Id = id;
            Name = name;
        }

        public int Id { get; }
        public string Name { get; }
    }

    public interface IRedDot
    {
        IReadOnlyList<RedDot_Record> All { get; }

        int Count { get; }

        RedDot_Record Get(int id);

        bool TryGet(int id, out RedDot_Record record);
    }
}
