// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;

namespace GamePlay
{
    public readonly struct Shop_Record
    {
        public Shop_Record(int id, string name, string desc, int itemId, int itemCount, System.Collections.Generic.IReadOnlyList<int> pos)
        {
            Id = id;
            Name = name;
            Desc = desc;
            ItemId = itemId;
            ItemCount = itemCount;
            Pos = pos;
        }

        public int Id { get; }
        public string Name { get; }
        public string Desc { get; }
        public int ItemId { get; }
        public int ItemCount { get; }
        public System.Collections.Generic.IReadOnlyList<int> Pos { get; }
    }

    public interface IShop
    {
        IReadOnlyList<Shop_Record> All { get; }

        int Count { get; }

        Shop_Record Get(int id);

        bool TryGet(int id, out Shop_Record record);
    }
}
