// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;
using GameFramework;

namespace GamePlay
{
    public sealed class RedDotTableAccess : IRedDot
    {
        private readonly cfg.json.TbRedDot _json;
        private readonly cfg.bin.TbRedDot _bin;
        private readonly bool _jsonMode;
        private readonly List<RedDot_Record> _all;

        private RedDotTableAccess(cfg.json.TbRedDot json)
        {
            _jsonMode = true;
            _json = json;
            _all = new List<RedDot_Record>(json.DataList.Count);
            foreach (cfg.json.RedDot row in json.DataList)
                _all.Add(ToRecord(row));
        }

        private RedDotTableAccess(cfg.bin.TbRedDot bin)
        {
            _jsonMode = false;
            _bin = bin;
            _all = new List<RedDot_Record>(bin.DataList.Count);
            foreach (cfg.bin.RedDot row in bin.DataList)
                _all.Add(ToRecord(row));
        }

        public IReadOnlyList<RedDot_Record> All => _all;

        public int Count => _all.Count;

        public static RedDotTableAccess From(cfg.json.TbRedDot table)
        {
            if (table == null)
                throw new GameFrameworkException("TbRedDot is invalid.");
            return new RedDotTableAccess(table);
        }

        public static RedDotTableAccess From(cfg.bin.TbRedDot table)
        {
            if (table == null)
                throw new GameFrameworkException("TbRedDot is invalid.");
            return new RedDotTableAccess(table);
        }

        public RedDot_Record Get(int id)
        {
            if (_jsonMode)
                return ToRecord(_json.Get(id));
            return ToRecord(_bin.Get(id));
        }

        public bool TryGet(int id, out RedDot_Record record)
        {
            if (_jsonMode)
            {
                if (!_json.DataMap.TryGetValue(id, out cfg.json.RedDot row) || row == null)
                {
                    record = default;
                    return false;
                }

                record = ToRecord(row);
                return true;
            }

            if (!_bin.DataMap.TryGetValue(id, out cfg.bin.RedDot rowBin) || rowBin == null)
            {
                record = default;
                return false;
            }

            record = ToRecord(rowBin);
            return true;
        }

        private static RedDot_Record ToRecord(cfg.json.RedDot row)
        {
            return new RedDot_Record(row.Id, row.Name);
        }

        private static RedDot_Record ToRecord(cfg.bin.RedDot row)
        {
            return new RedDot_Record(row.Id, row.Name);
        }
    }
}
