// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;
using GameFramework;

namespace GamePlay
{
    public sealed class ShopTableAccess : IShop
    {
        private readonly cfg.json.TbShop _json;
        private readonly cfg.bin.TbShop _bin;
        private readonly bool _jsonMode;
        private readonly List<Shop_Record> _all;

        private ShopTableAccess(cfg.json.TbShop json)
        {
            _jsonMode = true;
            _json = json;
            _all = new List<Shop_Record>(json.DataList.Count);
            foreach (cfg.json.Shop row in json.DataList)
                _all.Add(ToRecord(row));
        }

        private ShopTableAccess(cfg.bin.TbShop bin)
        {
            _jsonMode = false;
            _bin = bin;
            _all = new List<Shop_Record>(bin.DataList.Count);
            foreach (cfg.bin.Shop row in bin.DataList)
                _all.Add(ToRecord(row));
        }

        public IReadOnlyList<Shop_Record> All => _all;

        public int Count => _all.Count;

        public static ShopTableAccess From(cfg.json.TbShop table)
        {
            if (table == null)
                throw new GameFrameworkException("TbShop is invalid.");
            return new ShopTableAccess(table);
        }

        public static ShopTableAccess From(cfg.bin.TbShop table)
        {
            if (table == null)
                throw new GameFrameworkException("TbShop is invalid.");
            return new ShopTableAccess(table);
        }

        public Shop_Record Get(int id)
        {
            if (_jsonMode)
                return ToRecord(_json.Get(id));
            return ToRecord(_bin.Get(id));
        }

        public bool TryGet(int id, out Shop_Record record)
        {
            if (_jsonMode)
            {
                if (!_json.DataMap.TryGetValue(id, out cfg.json.Shop row) || row == null)
                {
                    record = default;
                    return false;
                }

                record = ToRecord(row);
                return true;
            }

            if (!_bin.DataMap.TryGetValue(id, out cfg.bin.Shop rowBin) || rowBin == null)
            {
                record = default;
                return false;
            }

            record = ToRecord(rowBin);
            return true;
        }

        private static Shop_Record ToRecord(cfg.json.Shop row)
        {
            return new Shop_Record(row.Id, row.Name, row.Desc, row.Item.ItemId, row.Item.Count, row.Pos);
        }

        private static Shop_Record ToRecord(cfg.bin.Shop row)
        {
            return new Shop_Record(row.Id, row.Name, row.Desc, row.Item.ItemId, row.Item.Count, row.Pos);
        }
    }
}
