// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;
using GameFramework;

namespace GamePlay
{
    public sealed class SoundTableAccess : ISound
    {
        private readonly cfg.json.TbSound _json;
        private readonly cfg.bin.TbSound _bin;
        private readonly bool _jsonMode;
        private readonly List<Sound_Record> _all;

        private SoundTableAccess(cfg.json.TbSound json)
        {
            _jsonMode = true;
            _json = json;
            _all = new List<Sound_Record>(json.DataList.Count);
            foreach (cfg.json.Sound row in json.DataList)
                _all.Add(ToRecord(row));
        }

        private SoundTableAccess(cfg.bin.TbSound bin)
        {
            _jsonMode = false;
            _bin = bin;
            _all = new List<Sound_Record>(bin.DataList.Count);
            foreach (cfg.bin.Sound row in bin.DataList)
                _all.Add(ToRecord(row));
        }

        public IReadOnlyList<Sound_Record> All => _all;

        public int Count => _all.Count;

        public static SoundTableAccess From(cfg.json.TbSound table)
        {
            if (table == null)
                throw new GameFrameworkException("TbSound is invalid.");
            return new SoundTableAccess(table);
        }

        public static SoundTableAccess From(cfg.bin.TbSound table)
        {
            if (table == null)
                throw new GameFrameworkException("TbSound is invalid.");
            return new SoundTableAccess(table);
        }

        public Sound_Record Get(int id)
        {
            if (_jsonMode)
                return ToRecord(_json.Get(id));
            return ToRecord(_bin.Get(id));
        }

        public bool TryGet(int id, out Sound_Record record)
        {
            if (_jsonMode)
            {
                if (!_json.DataMap.TryGetValue(id, out cfg.json.Sound row) || row == null)
                {
                    record = default;
                    return false;
                }

                record = ToRecord(row);
                return true;
            }

            if (!_bin.DataMap.TryGetValue(id, out cfg.bin.Sound rowBin) || rowBin == null)
            {
                record = default;
                return false;
            }

            record = ToRecord(rowBin);
            return true;
        }

        private static Sound_Record ToRecord(cfg.json.Sound row)
        {
            return new Sound_Record(row.Id, row.Location, row.Group, row.Loop, row.Volume, row.Priority, row.Mute, row.FadeInSeconds, row.Pitch, row.PanStereo, row.SpatialBlend, row.MaxDistance, row.DopplerLevel);
        }

        private static Sound_Record ToRecord(cfg.bin.Sound row)
        {
            return new Sound_Record(row.Id, row.Location, row.Group, row.Loop, row.Volume, row.Priority, row.Mute, row.FadeInSeconds, row.Pitch, row.PanStereo, row.SpatialBlend, row.MaxDistance, row.DopplerLevel);
        }
    }
}
