// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;
using GameFramework;

namespace GamePlay
{
    public sealed class SoundGroupTableAccess : ISoundGroup
    {
        private readonly cfg.json.TbSoundGroup _json;
        private readonly cfg.bin.TbSoundGroup _bin;
        private readonly bool _jsonMode;
        private readonly List<SoundGroup_Record> _all;

        private SoundGroupTableAccess(cfg.json.TbSoundGroup json)
        {
            _jsonMode = true;
            _json = json;
            _all = new List<SoundGroup_Record>(json.DataList.Count);
            foreach (cfg.json.SoundGroup row in json.DataList)
                _all.Add(ToRecord(row));
        }

        private SoundGroupTableAccess(cfg.bin.TbSoundGroup bin)
        {
            _jsonMode = false;
            _bin = bin;
            _all = new List<SoundGroup_Record>(bin.DataList.Count);
            foreach (cfg.bin.SoundGroup row in bin.DataList)
                _all.Add(ToRecord(row));
        }

        public IReadOnlyList<SoundGroup_Record> All => _all;

        public int Count => _all.Count;

        public static SoundGroupTableAccess From(cfg.json.TbSoundGroup table)
        {
            if (table == null)
                throw new GameFrameworkException("TbSoundGroup is invalid.");
            return new SoundGroupTableAccess(table);
        }

        public static SoundGroupTableAccess From(cfg.bin.TbSoundGroup table)
        {
            if (table == null)
                throw new GameFrameworkException("TbSoundGroup is invalid.");
            return new SoundGroupTableAccess(table);
        }

        public SoundGroup_Record Get(int id)
        {
            if (_jsonMode)
                return ToRecord(_json.Get(id));
            return ToRecord(_bin.Get(id));
        }

        public bool TryGet(int id, out SoundGroup_Record record)
        {
            if (_jsonMode)
            {
                if (!_json.DataMap.TryGetValue(id, out cfg.json.SoundGroup row) || row == null)
                {
                    record = default;
                    return false;
                }

                record = ToRecord(row);
                return true;
            }

            if (!_bin.DataMap.TryGetValue(id, out cfg.bin.SoundGroup rowBin) || rowBin == null)
            {
                record = default;
                return false;
            }

            record = ToRecord(rowBin);
            return true;
        }

        private static SoundGroup_Record ToRecord(cfg.json.SoundGroup row)
        {
            return new SoundGroup_Record(row.Id, row.Name, row.MixerGroupPath, row.AvoidBeingReplacedBySamePriority, row.Mute, row.Volume, row.AgentCount);
        }

        private static SoundGroup_Record ToRecord(cfg.bin.SoundGroup row)
        {
            return new SoundGroup_Record(row.Id, row.Name, row.MixerGroupPath, row.AvoidBeingReplacedBySamePriority, row.Mute, row.Volume, row.AgentCount);
        }
    }
}
