
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.json
{
public sealed partial class Weapon : Luban.BeanBase
{
    public Weapon(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["price"].IsNumber) { throw new SerializationException(); }  Price = _buf["price"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
    }

    public static Weapon DeserializeWeapon(JSONNode _buf)
    {
        return new Weapon(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// price
    /// </summary>
    public readonly int Price;
    /// <summary>
    /// name
    /// </summary>
    public readonly string Name;
   
    public const int __ID__ = -1707954628;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "price:" + Price + ","
        + "name:" + Name + ","
        + "}";
    }
}
}

