
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.json
{
public sealed partial class Shop : Luban.BeanBase
{
    public Shop(JSONNode _buf) 
    {
        { if(!_buf["id"].IsNumber) { throw new SerializationException(); }  Id = _buf["id"]; }
        { if(!_buf["name"].IsString) { throw new SerializationException(); }  Name = _buf["name"]; }
        { if(!_buf["desc"].IsString) { throw new SerializationException(); }  Desc = _buf["desc"]; }
        { if(!_buf["item"].IsObject) { throw new SerializationException(); }  Item = global::cfg.json.ShopDef.MyItem.DeserializeMyItem(_buf["item"]);  }
        { var __json0 = _buf["pos"]; if(!__json0.IsArray) { throw new SerializationException(); } Pos = new System.Collections.Generic.List<int>(__json0.Count); foreach(JSONNode __e0 in __json0.Children) { int __v0;  { if(!__e0.IsNumber) { throw new SerializationException(); }  __v0 = __e0; }  Pos.Add(__v0); }   }
    }

    public static Shop DeserializeShop(JSONNode _buf)
    {
        return new Shop(_buf);
    }

    /// <summary>
    /// id
    /// </summary>
    public readonly int Id;
    /// <summary>
    /// 名称
    /// </summary>
    public readonly string Name;
    /// <summary>
    /// 描述
    /// </summary>
    public readonly string Desc;
    /// <summary>
    /// item_id
    /// </summary>
    public readonly ShopDef.MyItem Item;
    /// <summary>
    /// 位置
    /// </summary>
    public readonly System.Collections.Generic.List<int> Pos;
   
    public const int __ID__ = 2576150;
    public override int GetTypeId() => __ID__;

    public  void ResolveRef(Tables tables)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "id:" + Id + ","
        + "name:" + Name + ","
        + "desc:" + Desc + ","
        + "item:" + Item + ","
        + "pos:" + Luban.StringUtil.CollectionToString(Pos) + ","
        + "}";
    }
}
}

