
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.json
{
public partial class TbRedDot
{
    private readonly System.Collections.Generic.Dictionary<int, RedDot> _dataMap;
    private readonly System.Collections.Generic.List<RedDot> _dataList;
    
    public TbRedDot(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, RedDot>(count);
        _dataList = new System.Collections.Generic.List<RedDot>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            RedDot _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.json.RedDot.DeserializeRedDot(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, RedDot> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<RedDot> DataList => _dataList;

    public RedDot GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public RedDot Get(int key) => _dataMap[key];
    public RedDot this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

