
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using Luban;
using Luban.SimpleJSON;


namespace cfg.json
{
public partial class TbSound
{
    private readonly System.Collections.Generic.Dictionary<int, Sound> _dataMap;
    private readonly System.Collections.Generic.List<Sound> _dataList;
    
    public TbSound(JSONNode _buf)
    {
        int count = _buf.Count;
        _dataMap = new System.Collections.Generic.Dictionary<int, Sound>(count);
        _dataList = new System.Collections.Generic.List<Sound>(count);
        
        foreach(JSONNode _ele in _buf.Children)
        {
            Sound _v;
            { if(!_ele.IsObject) { throw new SerializationException(); }  _v = global::cfg.json.Sound.DeserializeSound(_ele);  }
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
    }

    public System.Collections.Generic.IReadOnlyDictionary<int, Sound> DataMap => _dataMap;
    public System.Collections.Generic.IReadOnlyList<Sound> DataList => _dataList;

    public Sound GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : default;
    public Sound Get(int key) => _dataMap[key];
    public Sound this[int key] => _dataMap[key];

    public void ResolveRef(Tables tables)
    {
        foreach(var _v in _dataList)
        {
            _v.ResolveRef(tables);
        }
    }

}

}

