// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;

namespace GamePlay
{
    public readonly struct SoundGroup_Record
    {
        public SoundGroup_Record(int id, string name, string mixerGroupPath, bool avoidBeingReplacedBySamePriority, bool mute, float volume, int agentCount)
        {
            Id = id;
            Name = name;
            MixerGroupPath = mixerGroupPath;
            AvoidBeingReplacedBySamePriority = avoidBeingReplacedBySamePriority;
            Mute = mute;
            Volume = volume;
            AgentCount = agentCount;
        }

        public int Id { get; }
        public string Name { get; }
        public string MixerGroupPath { get; }
        public bool AvoidBeingReplacedBySamePriority { get; }
        public bool Mute { get; }
        public float Volume { get; }
        public int AgentCount { get; }
    }

    public interface ISoundGroup
    {
        IReadOnlyList<SoundGroup_Record> All { get; }

        int Count { get; }

        SoundGroup_Record Get(int id);

        bool TryGet(int id, out SoundGroup_Record record);
    }
}
