// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;

namespace GamePlay
{
    public readonly struct Sound_Record
    {
        public Sound_Record(int id, string location, string group, bool loop, float volume, int priority, bool mute, float fadeInSeconds, float pitch, float panStereo, float spatialBlend, float maxDistance, float dopplerLevel)
        {
            Id = id;
            Location = location;
            Group = group;
            Loop = loop;
            Volume = volume;
            Priority = priority;
            Mute = mute;
            FadeInSeconds = fadeInSeconds;
            Pitch = pitch;
            PanStereo = panStereo;
            SpatialBlend = spatialBlend;
            MaxDistance = maxDistance;
            DopplerLevel = dopplerLevel;
        }

        public int Id { get; }
        public string Location { get; }
        public string Group { get; }
        public bool Loop { get; }
        public float Volume { get; }
        public int Priority { get; }
        public bool Mute { get; }
        public float FadeInSeconds { get; }
        public float Pitch { get; }
        public float PanStereo { get; }
        public float SpatialBlend { get; }
        public float MaxDistance { get; }
        public float DopplerLevel { get; }
    }

    public interface ISound
    {
        IReadOnlyList<Sound_Record> All { get; }

        int Count { get; }

        Sound_Record Get(int id);

        bool TryGet(int id, out Sound_Record record);
    }
}
