// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;

namespace GamePlay
{
    public readonly struct UIPanel_Record
    {
        public UIPanel_Record(int id, string location, string desc, string groupName, int canvasMode, int sortOrder, bool pauseCoveredUIForm, int loader)
        {
            Id = id;
            Location = location;
            Desc = desc;
            GroupName = groupName;
            CanvasMode = canvasMode;
            SortOrder = sortOrder;
            PauseCoveredUIForm = pauseCoveredUIForm;
            Loader = loader;
        }

        public int Id { get; }
        public string Location { get; }
        public string Desc { get; }
        public string GroupName { get; }
        public int CanvasMode { get; }
        public int SortOrder { get; }
        public bool PauseCoveredUIForm { get; }
        public int Loader { get; }
    }

    public interface IUIPanel
    {
        IReadOnlyList<UIPanel_Record> All { get; }

        int Count { get; }

        UIPanel_Record Get(int id);

        bool TryGet(int id, out UIPanel_Record record);
    }
}
