// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;

namespace GamePlay
{
    public readonly struct Weapon_Record
    {
        public Weapon_Record(int id, int price, string name)
        {
            Id = id;
            Price = price;
            Name = name;
        }

        public int Id { get; }
        public int Price { get; }
        public string Name { get; }
    }

    public interface IWeapon
    {
        IReadOnlyList<Weapon_Record> All { get; }

        int Count { get; }

        Weapon_Record Get(int id);

        bool TryGet(int id, out Weapon_Record record);
    }
}
