// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;
using System.Threading;
using Cysharp.Threading.Tasks;
using GameFramework;
using Luban;
using Luban.SimpleJSON;

namespace GamePlay
{
    public sealed class LubanTablesFactory : ILubanTablesFactory
    {
        private static readonly string[] TABLE_LOCATIONS = { "tbsound", "tbsoundgroup", "tbuipanel", "tbweapon" };

        public async UniTask<LubanTableRegistry> CreateAsync(
            LubanDataMode mode,
            ILubanDataLoader loader,
            CancellationToken cancellationToken = default)
        {
            if (loader == null)
                throw new GameFrameworkException("Luban data loader is invalid.");

            var registry = new LubanTableRegistry();

            if (mode == LubanDataMode.Json)
            {
                var cache = new Dictionary<string, string>(TABLE_LOCATIONS.Length);
                foreach (string location in TABLE_LOCATIONS)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    cache[location] = await loader.LoadTextAsync(location, cancellationToken);
                }

                var tables = new cfg.json.Tables(name => JSON.Parse(cache[name]));
                registry.Register<ISound>(SoundTableAccess.From(tables.TbSound));
                registry.Register<ISoundGroup>(SoundGroupTableAccess.From(tables.TbSoundGroup));
                registry.Register<IUIPanel>(UIPanelTableAccess.From(tables.TbUIPanel));
                registry.Register<IWeapon>(WeaponTableAccess.From(tables.TbWeapon));
                return registry;
            }

            if (mode == LubanDataMode.Binary)
            {
                var cache = new Dictionary<string, byte[]>(TABLE_LOCATIONS.Length);
                foreach (string location in TABLE_LOCATIONS)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    cache[location] = await loader.LoadBytesAsync(location, cancellationToken);
                }

                var tables = new cfg.bin.Tables(name => new ByteBuf(cache[name]));
                registry.Register<ISound>(SoundTableAccess.From(tables.TbSound));
                registry.Register<ISoundGroup>(SoundGroupTableAccess.From(tables.TbSoundGroup));
                registry.Register<IUIPanel>(UIPanelTableAccess.From(tables.TbUIPanel));
                registry.Register<IWeapon>(WeaponTableAccess.From(tables.TbWeapon));
                return registry;
            }

            throw new GameFrameworkException(Utility.Text.Format("Unsupported LubanDataMode: {0}", mode));
        }
    }
}
