// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;
using GameFramework;

namespace GamePlay
{
    public sealed class UIPanelTableAccess : IUIPanel
    {
        private readonly cfg.json.TbUIPanel _json;
        private readonly cfg.bin.TbUIPanel _bin;
        private readonly bool _jsonMode;
        private readonly List<UIPanel_Record> _all;

        private UIPanelTableAccess(cfg.json.TbUIPanel json)
        {
            _jsonMode = true;
            _json = json;
            _all = new List<UIPanel_Record>(json.DataList.Count);
            foreach (cfg.json.UIPanel row in json.DataList)
                _all.Add(ToRecord(row));
        }

        private UIPanelTableAccess(cfg.bin.TbUIPanel bin)
        {
            _jsonMode = false;
            _bin = bin;
            _all = new List<UIPanel_Record>(bin.DataList.Count);
            foreach (cfg.bin.UIPanel row in bin.DataList)
                _all.Add(ToRecord(row));
        }

        public IReadOnlyList<UIPanel_Record> All => _all;

        public int Count => _all.Count;

        public static UIPanelTableAccess From(cfg.json.TbUIPanel table)
        {
            if (table == null)
                throw new GameFrameworkException("TbUIPanel is invalid.");
            return new UIPanelTableAccess(table);
        }

        public static UIPanelTableAccess From(cfg.bin.TbUIPanel table)
        {
            if (table == null)
                throw new GameFrameworkException("TbUIPanel is invalid.");
            return new UIPanelTableAccess(table);
        }

        public UIPanel_Record Get(int id)
        {
            if (_jsonMode)
                return ToRecord(_json.Get(id));
            return ToRecord(_bin.Get(id));
        }

        public bool TryGet(int id, out UIPanel_Record record)
        {
            if (_jsonMode)
            {
                if (!_json.DataMap.TryGetValue(id, out cfg.json.UIPanel row) || row == null)
                {
                    record = default;
                    return false;
                }

                record = ToRecord(row);
                return true;
            }

            if (!_bin.DataMap.TryGetValue(id, out cfg.bin.UIPanel rowBin) || rowBin == null)
            {
                record = default;
                return false;
            }

            record = ToRecord(rowBin);
            return true;
        }

        private static UIPanel_Record ToRecord(cfg.json.UIPanel row)
        {
            return new UIPanel_Record(row.Id, row.Location, row.Desc, row.GroupName, row.CanvasMode, row.SortOrder, row.PauseCoveredUIForm, row.Loader);
        }

        private static UIPanel_Record ToRecord(cfg.bin.UIPanel row)
        {
            return new UIPanel_Record(row.Id, row.Location, row.Desc, row.GroupName, row.CanvasMode, row.SortOrder, row.PauseCoveredUIForm, row.Loader);
        }
    }
}
