// <auto-generated by gen_adapters.ps1>
using System.Collections.Generic;
using GameFramework;

namespace GamePlay
{
    public sealed class WeaponTableAccess : IWeapon
    {
        private readonly cfg.json.TbWeapon _json;
        private readonly cfg.bin.TbWeapon _bin;
        private readonly bool _jsonMode;
        private readonly List<Weapon_Record> _all;

        private WeaponTableAccess(cfg.json.TbWeapon json)
        {
            _jsonMode = true;
            _json = json;
            _all = new List<Weapon_Record>(json.DataList.Count);
            foreach (cfg.json.Weapon row in json.DataList)
                _all.Add(ToRecord(row));
        }

        private WeaponTableAccess(cfg.bin.TbWeapon bin)
        {
            _jsonMode = false;
            _bin = bin;
            _all = new List<Weapon_Record>(bin.DataList.Count);
            foreach (cfg.bin.Weapon row in bin.DataList)
                _all.Add(ToRecord(row));
        }

        public IReadOnlyList<Weapon_Record> All => _all;

        public int Count => _all.Count;

        public static WeaponTableAccess From(cfg.json.TbWeapon table)
        {
            if (table == null)
                throw new GameFrameworkException("TbWeapon is invalid.");
            return new WeaponTableAccess(table);
        }

        public static WeaponTableAccess From(cfg.bin.TbWeapon table)
        {
            if (table == null)
                throw new GameFrameworkException("TbWeapon is invalid.");
            return new WeaponTableAccess(table);
        }

        public Weapon_Record Get(int id)
        {
            if (_jsonMode)
                return ToRecord(_json.Get(id));
            return ToRecord(_bin.Get(id));
        }

        public bool TryGet(int id, out Weapon_Record record)
        {
            if (_jsonMode)
            {
                if (!_json.DataMap.TryGetValue(id, out cfg.json.Weapon row) || row == null)
                {
                    record = default;
                    return false;
                }

                record = ToRecord(row);
                return true;
            }

            if (!_bin.DataMap.TryGetValue(id, out cfg.bin.Weapon rowBin) || rowBin == null)
            {
                record = default;
                return false;
            }

            record = ToRecord(rowBin);
            return true;
        }

        private static Weapon_Record ToRecord(cfg.json.Weapon row)
        {
            return new Weapon_Record(row.Id, row.Price, row.Name);
        }

        private static Weapon_Record ToRecord(cfg.bin.Weapon row)
        {
            return new Weapon_Record(row.Id, row.Price, row.Name);
        }
    }
}
